apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ims-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: controlplane
      containers:
        - name: backend
          image: ims-zeotap-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: ims-secret
          readinessProbe:
            httpGet:
              path: /api/incidents
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ims-app
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
